/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cropper;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ImageCropAppTest {
    @Test
    void appHasAGreeting() {
        ImageCropApp classUnderTest = new ImageCropApp();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
